import { useEffect, useState, type FormEvent } from "react";
import { getProfileForAdmin, updateProfile } from "../../../services/adminProfile";

type ContactForm = { alamat: string; maps_url: string; telepon: string; email: string; jam_pelayanan: string; instagram_url: string; facebook_url: string; youtube_url: string; website_url: string };
const empty: ContactForm = { alamat: "", maps_url: "", telepon: "", email: "", jam_pelayanan: "", instagram_url: "", facebook_url: "", youtube_url: "", website_url: "" };
const inputClass = "h-12 w-full rounded-xl border border-[#C8D5D0] bg-white px-4 text-[14px] text-[#173F57] outline-none focus:border-[#0D6F6B] focus:ring-2 focus:ring-[#0D6F6B]/15";
const urlFields = ["maps_url", "instagram_url", "facebook_url", "youtube_url", "website_url"] as const;
function validUrl(value: string) { if (!value.trim()) return true; try { return ["http:", "https:"].includes(new URL(value).protocol); } catch { return false; } }

export default function AdminContactPage() {
  const [form, setForm] = useState(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [validation, setValidation] = useState<Record<string,string>>({});
  useEffect(() => { let active = true; getProfileForAdmin().then((p) => active && setForm({ alamat:p.alamat??"", maps_url:p.maps_url??"", telepon:p.telepon??"", email:p.email??"", jam_pelayanan:p.jam_pelayanan??"", instagram_url:p.instagram_url??"", facebook_url:p.facebook_url??"", youtube_url:p.youtube_url??"", website_url:p.website_url??"" })).catch(() => active && setError("Kontak belum dapat dimuat. Silakan coba lagi.")).finally(() => active && setLoading(false)); return () => { active=false; }; }, []);
  const change=(key:keyof ContactForm,value:string)=>{setForm(c=>({...c,[key]:value}));setValidation(c=>({...c,[key]:""}));};
  async function submit(event:FormEvent){event.preventDefault();const next:Record<string,string>={};if(form.email.trim()&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim()))next.email="Format email belum valid.";urlFields.forEach(k=>{if(!validUrl(form[k]))next[k]="Gunakan URL http atau https yang valid.";});setValidation(next);if(Object.keys(next).length)return;setSaving(true);setMessage("");setError("");try{const nullable=(v:string)=>v.trim()||null;await updateProfile({alamat:nullable(form.alamat),maps_url:nullable(form.maps_url),telepon:nullable(form.telepon),email:nullable(form.email),jam_pelayanan:nullable(form.jam_pelayanan),instagram_url:nullable(form.instagram_url),facebook_url:nullable(form.facebook_url),youtube_url:nullable(form.youtube_url),website_url:nullable(form.website_url)});setMessage("Kontak berhasil diperbarui.");}catch{setError("Kontak belum dapat disimpan. Silakan coba lagi.");}finally{setSaving(false);}}
  if(loading)return <p className="rounded-2xl border border-[#D8E4DF] bg-white px-6 py-12 text-center text-[14px] text-[#5F6F72]">Memuat Kontak…</p>;
  return <section className="max-w-3xl"><h1 className="text-[1.75rem] font-bold text-[#173F57]">Kontak</h1><p className="mt-2 text-[14px] text-[#5F6F72]">Perubahan pada halaman ini akan tampil pada menu Kontak website.</p>{message&&<p className="mt-6 rounded-xl bg-emerald-50 px-4 py-3 text-[14px] text-emerald-700">{message}</p>}{error&&<p className="mt-6 rounded-xl bg-red-50 px-4 py-3 text-[14px] text-red-700">{error}</p>}
    <form onSubmit={submit} className="mt-6 space-y-5 rounded-2xl border border-[#D8E4DF] bg-white p-5 sm:p-7"><Field label="Alamat"><textarea className={`${inputClass} min-h-24 resize-y py-3`} value={form.alamat} onChange={e=>change("alamat",e.target.value)}/></Field><Field label="Google Maps" error={validation.maps_url}><input className={inputClass} value={form.maps_url} onChange={e=>change("maps_url",e.target.value)}/></Field><Field label="WhatsApp"><input type="tel" className={inputClass} value={form.telepon} onChange={e=>change("telepon",e.target.value)}/></Field><Field label="Email" error={validation.email}><input type="email" className={inputClass} value={form.email} onChange={e=>change("email",e.target.value)}/></Field><Field label="Jam Pelayanan"><input className={inputClass} value={form.jam_pelayanan} onChange={e=>change("jam_pelayanan",e.target.value)}/></Field>{urlFields.slice(1).map(key=><Field key={key} label={({instagram_url:"Instagram",facebook_url:"Facebook",youtube_url:"YouTube",website_url:"Website"} as Record<string,string>)[key]} error={validation[key]}><input className={inputClass} value={form[key]} onChange={e=>change(key,e.target.value)}/></Field>)}<button disabled={saving} className="min-h-12 w-full rounded-xl bg-[#0D6F6B] text-[14px] font-bold text-white disabled:opacity-60">{saving?"Menyimpan…":"Simpan Perubahan"}</button></form></section>;
}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-[14px] font-semibold text-[#294B55]">{label}</span>{children}{error&&<span className="mt-1 block text-[12px] text-red-600">{error}</span>}</label>;}
